# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XJRxkYWyXgYHDmKWeNERPap_W2Uwv7vR
"""

# Save Model Using joblib
import pandas
from sklearn import model_selection
from sklearn.linear_model import LogisticRegression
import joblib



# load the model from url/path
filename = 'modelfinalized_model.sav'
loaded_model = joblib.load(filename)
#result = loaded_model.score(X_test, Y_test)
loaded_model.summary()

#result = loaded_model.evaluate()
#print(result)

