#!/bin/bash
# Test script to demonstrate k-fold testing in nnTester

echo "=== K-Fold Testing Usage Guide ==="
echo ""
echo "The nnTester now supports k-fold cross-validation testing with two new options:"
echo ""
echo "1. --kfold=N   : Test N folds and aggregate results"
echo "2. --rerun     : Re-run tests even if results exist"
echo ""
echo "Example commands:"
echo ""
echo "# Test 5 folds (use existing results if available)"
echo "python user_tools/nnTraining2/nnTester.py --config nnConfig.json --kfold=5"
echo ""
echo "# Test 5 folds and re-run all tests"
echo "python user_tools/nnTraining2/nnTester.py --config nnConfig.json --kfold=5 --rerun"
echo ""
echo "# Test single model (original behavior, no k-fold)"
echo "python user_tools/nnTraining2/nnTester.py --config nnConfig.json"
echo ""
echo "Features:"
echo "  - Automatically validates that all fold directories exist"
echo "  - Raises error if specified kfold doesn't match actual fold count"
echo "  - Computes mean and standard deviation across all folds"
echo "  - Saves summary to kfold_summary.txt and kfold_summary.json"
echo "  - Can use existing testResults.json from each fold (fast)"
echo "  - Can re-run all tests with --rerun flag"
echo ""
echo "Directory structure expected:"
echo "  ./fold0/testResults.json"
echo "  ./fold1/testResults.json"
echo "  ./fold2/testResults.json"
echo "  ..."
echo ""
echo "Output files:"
echo "  ./kfold_summary.txt  - Human-readable summary"
echo "  ./kfold_summary.json - Machine-readable summary with all data"
